#!/usr/bin/env bash
# Hits the running API in a loop so logs/traces/metrics have real data to look at.
# Mix: 201 create, 200 list/get, 200 update, 204 delete, 400 validation, 400 bad id, 404 not found.
set -euo pipefail

API="${API_URL:-http://localhost:8080}"
DURATION="${DURATION:-60}"   # seconds
INTERVAL="${INTERVAL:-1}"    # seconds between each loop iteration

echo "Generating traffic against $API for ${DURATION}s (ctrl-c to stop early)..."

end=$((SECONDS + DURATION))
while [ "$SECONDS" -lt "$end" ]; do
  created_id=$(curl -s -X POST "$API/api/v1/tasks/" \
    -H 'Content-Type: application/json' \
    -d '{"title":"demo task","description":"generated by traffic script","done":false}' \
    | sed -n 's/.*"id":\([0-9]*\).*/\1/p')

  curl -s -o /dev/null "$API/api/v1/tasks/"
  curl -s -o /dev/null "$API/api/v1/tasks/1"

  if [ -n "$created_id" ]; then
    curl -s -o /dev/null -X PUT "$API/api/v1/tasks/$created_id" \
      -H 'Content-Type: application/json' \
      -d '{"title":"demo task updated","description":"updated by traffic script","done":true}'
    curl -s -o /dev/null -X DELETE "$API/api/v1/tasks/$created_id"
  fi

  curl -s -o /dev/null -X POST "$API/api/v1/tasks/" \
    -H 'Content-Type: application/json' \
    -d '{"description":"missing title triggers 400"}'

  curl -s -o /dev/null "$API/api/v1/tasks/notanumber"
  curl -s -o /dev/null "$API/api/v1/tasks/999999"

  sleep "$INTERVAL"
done

echo "Done."
